### ISSUE TITLE
TV show treeview: Icon alignment glitchy

### ISSUE THREAD

**Issue by hirnsushi** [Komet/MediaElch#478]
MediaElch_linux_2.4.3-dev_2018-06-18_17-19_git-master-a63b5bc

I noticed a small glitch with the TV show icons when first opening Media Elch. Maximizing and unmaximizing again pushes them to the side and fixes it (but cuts them off obviously).
![grafik](https://user-images.githubusercontent.com/5706729/41554176-565c71cc-7334-11e8-8b39-39c84d8da596.png)
![grafik](https://user-images.githubusercontent.com/5706729/41554264-a104cdb4-7334-11e8-92fa-344dd6f65aa9.png)

**Comment by bugwelle** [comment]
I've fixed this in my development branch. I'll push my changes to this repository as soon as #477 is merged (because my changes depend on those).

![screenshot_20180620_133012](https://user-images.githubusercontent.com/1667306/41655775-4430f95e-748e-11e8-9c26-09736d3ca635.png)

`QTreeView` is a bit tricky to work with. I still need to test this on Mac and Windows. :smiley:

**Comment by hirnsushi** [comment]
Sadly I still have some issues with that. Somehow the icon spacing is completely off on my system
![grafik](https://user-images.githubusercontent.com/5706729/42182123-82dec2fe-7e3d-11e8-8457-debab8c789b8.png)
I have no idea what's causing this or if I'm maybe the only one experiencing this, but the icons have always been that far apart since I've been using MediaElch. Let me know if I can do anything to track that down.
