### ISSUE TITLE
Audio media info

### ISSUE THREAD

**Issue by azriel84** [Komet/MediaElch#797]
I don't know if this is a bug or just how things are now, but with latest 2.6.2 stable, audio information are just a plain 7.1 or 5.1 etc. No codec information like Dolby Atmos, DTS-HD etc whatsoever. Can this change in the future?

**Comment by monisriz** [comment]
It should be fixed with the PR (https://github.com/Komet/MediaElch/pull/794). I already created an issue for this (https://github.com/Komet/MediaElch/issues/796).

**Comment by azriel84** [comment]
I don't know what PR is but thank you very much for asnwering and fixing it! :)

**Comment by monisriz** [comment]
PR = pull request (changes to the code).
It's won't be fixed until the said PR is approved by @bugwelle, merged into the code and next version released. It'll be a while still..

**Comment by azriel84** [comment]
Patience is a virtue

**Comment by bugwelle** [comment]
I've just reviewed @monisriz pull request and it looks good to me (just one change request). I will merge the PR when it is updated and a new nightly version will be released automatically. :-)

Thank you for opening this issue, @azriel84 👍

**Comment by azriel84** [comment]
Awesome thanks for the update!

**Comment by monisriz** [comment]
This can be closed I think as it’s a duplicate of an existing issue.

**Comment by monisriz** [comment]
Resolved with https://github.com/Komet/MediaElch/pull/794. Closing.

**Comment by bugwelle** [comment]
Thanks. @azriel84 I think this issue should be fixed by the latest nightly version. :-)

**Comment by azriel84** [comment]
much appreciated!

**Comment by azriel84** [comment]
I know this is a closed issue but I installed the latest nightly build and the problem is still there. Any update of the matter please?

**Comment by bugwelle** [comment]
Hi,

could you tell use what MediaInfo version you are using, please? :)
You can see that in "MediaElch -> About -> Developer". It should be the last line in the text box. :)

**Comment by azriel84** [comment]
MediaInfo Version: MediaInfoLib - v19.04 on the latest nightly. I updated my standalone mediainfo version to 19.09 but didn't do anything on mediaelch. 

Just to be clear, using version 2.6.0, I get the proper sound info of my files for example "Dolby Atmos 7.1". With every later version, stable or developer, I get just the "7.1" icon.

**Comment by bugwelle** [comment]
Yeah, we changed some field names we load using MediaInfo. MediaInfo's documentation is very sparse and it's not very clear what fields should be used to get the info we want. I'll reopen this issue for. :)

**Comment by bugwelle** [comment]
#851 will most likely fix this issue :-)

**Comment by azriel84** [comment]
Excellent news, looking forward to it!
